### ISSUE TITLE
Error at program launch

### ISSUE THREAD

**Issue by suphamster** [kins-dev/rpgmaker_mv_decoder#1]
I'm on Win10x64, tried v0.3.3-1.4.0, this tool crashes right away when I click on "[RPGMaker.MV.Decoder.-.Encoder.exe](https://github.com/kins-dev/rpgmaker_mv_decoder/releases/download/v1.4.0/RPGMaker.MV.Decoder.-.Encoder.exe)"
```
Traceback (most recent call last):
  File "gui.py", line 18, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "rpgmaker_mv_decoder\projectdecoder.py", line 9, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "magic\__init__.py", line 209, in <module>
  File "magic\loader.py", line 49, in load_lib
ImportError: failed to find libmagic.  Check your installation
```
When I've compiled it by myself with Auto Py to Exe it shows same error

**Comment by suphamster** [comment]
Fixed after installing this https://github.com/pidydx/libmagicwin64
